export const START_REQUEST = "START_REQUEST";
export const SUCCESS_REQUEST = "SUCCESS_REQUEST";
export const FAIL_REQUEST = "FAIL_REQUEST";
export const SET_EPISODES = "SET_EPISODES";
export const SET_PODCASTS = "SET_PODCASTS";
